AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Enabled: false

Naming/MethodName:
  EnforcedStyle: snake_case

Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: true

Style/HashSyntax:
  Description: >-
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  Enabled: false
  EnforcedStyle: hash_rockets

Style/LineEndConcatenation:
  Description: 'Use \\ instead of + to concatenate two string literals at line end.'
  Enabled: true
  
Layout/LineLength:
  Description: 'Limit lines to 79 characters.'
  Enabled: true
  Max: 80

Metrics/CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: false
